services:

  _defaults:
    public: true
    autowire: true
    autoconfigure: true

  Redis:
    class: 'Redis'
    factory: 'RvltDigital\SymfonyRevoltaBundle\Service\RedisHandlerFactory:getInstance'
