services:

  _defaults:
    public: true
    autowire: true
    autoconfigure: true

  RvltDigital\SymfonyRevoltaBundle\:
    resource: '../*'
    exclude: '../{config,Entity,Interfaces,Traits,Validator,Exception}'

  Redis:
    class: 'Redis'
    factory: 'RvltDigital\SymfonyRevoltaBundle\Service\RedisHandlerFactory:getInstance'

  RvltDigital\SymfonyRevoltaBundle\Listener\FixDefaultSchemaListener:
    tags:
      - { name: doctrine.event_subscriber, connection: default }

  RvltDigital\SymfonyRevoltaBundle\Listener\ChangeTrackingPolicyListener:
    tags:
      - { name: doctrine.event_subscriber, connection: default }

  RvltDigital\SymfonyRevoltaBundle\Service\SlackLogger:
    arguments:
      - '%rvlt_digital.internal.revolta.slack_config%'

  doctrine.orm.validator.unique:
    class: RvltDigital\SymfonyRevoltaBundle\Validator\Constraints\UniqueEntityValidator

  logger:
    alias: 'monolog.logger'

  RvltDigital\SymfonyRevoltaBundle\Doctrine\NamingStrategy:
    arguments:
      - '@doctrine.orm.naming_strategy.underscore'
