services:

  _defaults:
    public: true
    autowire: true
    autoconfigure: true

  RvltDigital\SymfonyRevoltaBundle\:
    resource: '../*'
    exclude: '../{config,Entity,Interfaces,Traits}'

  Redis:
    class: 'Redis'
    factory: 'RvltDigital\SymfonyRevoltaBundle\Service\RedisHandlerFactory:getInstance'
