rvlt_digital_symfony_revolta:
  # The change tracking policy for Doctrine entities, if null then the default Doctrine behavior is used.
  # Allowed values: implicit, explicit, notify
  # See https://www.doctrine-project.org/projects/doctrine-orm/en/2.6/reference/change-tracking-policies.html
  change_tracking_policy: ~
  mailer:
    default_name: ''
    default_email: ''
